# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Raterunner < Formula
  desc "CLI tool for managing SaaS billing configurations as code"
  homepage "https://github.com/raterunner/cli"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raterunner/cli/releases/download/v0.0.1/raterunner_0.0.1_darwin_amd64.tar.gz"
      sha256 "5476e0e95ad8a8486f5d3cc695eed7279bca3055a1e2b0846de907867ed1c5a2"

      def install
        bin.install "raterunner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raterunner/cli/releases/download/v0.0.1/raterunner_0.0.1_darwin_arm64.tar.gz"
      sha256 "52c22cd48f87bbea143a727c146e8fbb430551a63792913b67b5bd9303289414"

      def install
        bin.install "raterunner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/raterunner/cli/releases/download/v0.0.1/raterunner_0.0.1_linux_amd64.tar.gz"
      sha256 "2f0cd6070a21f337d360e263727cf88eb44aff7bc1daeed65e9ff11123e7443b"
      def install
        bin.install "raterunner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raterunner/cli/releases/download/v0.0.1/raterunner_0.0.1_linux_arm64.tar.gz"
      sha256 "42080eecaf2a6aa6ac9ef06ecc88a37409d80e9ee34b145cce36d6480fcdc0a6"
      def install
        bin.install "raterunner"
      end
    end
  end

  test do
    system "#{bin}/raterunner", "--version"
  end
end
