# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Raterunner < Formula
  desc "CLI tool for managing SaaS billing configurations as code"
  homepage "https://github.com/raterunner/cli"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raterunner/cli/releases/download/v0.0.2/raterunner_0.0.2_darwin_amd64.tar.gz"
      sha256 "5260fd4d18741073bccf9a8d77094ff529166b21c2df6ec76ffd288278e2372c"

      def install
        bin.install "raterunner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raterunner/cli/releases/download/v0.0.2/raterunner_0.0.2_darwin_arm64.tar.gz"
      sha256 "04a9290a932ca46cdb75b3a72da40f7e2a97aa600a03d5bdff2aa516644eaede"

      def install
        bin.install "raterunner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/raterunner/cli/releases/download/v0.0.2/raterunner_0.0.2_linux_amd64.tar.gz"
      sha256 "b014e52d92ba07d102b55e7898f8d8fa24e23743c9b50d9d1963445609f603c6"
      def install
        bin.install "raterunner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raterunner/cli/releases/download/v0.0.2/raterunner_0.0.2_linux_arm64.tar.gz"
      sha256 "f76812a165d444528f9678cae3a24d07fd94e308cc3ddda9220ec59a085554ec"
      def install
        bin.install "raterunner"
      end
    end
  end

  test do
    system "#{bin}/raterunner", "--version"
  end
end
