# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Raterunner < Formula
  desc "CLI tool for managing SaaS billing configurations as code"
  homepage "https://github.com/raterunner/cli"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raterunner/cli/releases/download/v0.0.3/raterunner_0.0.3_darwin_amd64.tar.gz"
      sha256 "668ba1ef8cc232cbdd4e2d48ccafbb4cc8766ea5ca2282a9f66cb3a088180fd1"

      def install
        bin.install "raterunner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raterunner/cli/releases/download/v0.0.3/raterunner_0.0.3_darwin_arm64.tar.gz"
      sha256 "50861b5ab9e314453ff29236ff533ea1aa149bb4c27897fe6a41672d34b4a5c1"

      def install
        bin.install "raterunner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/raterunner/cli/releases/download/v0.0.3/raterunner_0.0.3_linux_amd64.tar.gz"
      sha256 "dd8a4afc9e541a4b868276e92a83d1507c9e97f98b47a449046b3d385e9e8aff"
      def install
        bin.install "raterunner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raterunner/cli/releases/download/v0.0.3/raterunner_0.0.3_linux_arm64.tar.gz"
      sha256 "5815d7641c14111b8608b9750a3d3a83f2c569328884e3e8e7a31405a928db87"
      def install
        bin.install "raterunner"
      end
    end
  end

  test do
    system "#{bin}/raterunner", "--version"
  end
end
